# Generated by Django 4.2 on 2024-04-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price_clp',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10),
            preserve_default=False,
        ),
    ]
